# Generated by Django 2.2.11 on 2020-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200319_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
